#include "PeripheralPins.h"
#include "mbed_toolchain.h"

//*** Motion Control ***

MBED_WEAK const PinMap PinMap_ADC[] = {
    // Thermistor inputs
    {PF_3,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 9, 0)},   // THERM0
    {PF_4,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 14, 0)},  // THERM1
    {PF_5,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 15, 0)},  // THERM2
    {PF_6,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 4, 0)},   // THERM3
    {PF_7,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 5, 0)},   // THERM4
    {PC_0,       ADC_1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 10, 0)},  // PWR_DET
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_ADC_Internal[] = {
    {NC, NC, 0}
};
//*** DAC ***

MBED_WEAK const PinMap PinMap_DAC[] = {
    // No DAC pins used on Octopus Pro
    {NC, NC, 0}
};

//*** UART Flow Control ***

MBED_WEAK const PinMap PinMap_UART_RTS[] = {
    // No RTS pins used on Octopus Pro
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_UART_CTS[] = {
    // No CTS pins used on Octopus Pro
    {NC, NC, 0}
};

//*** PWM ***

MBED_WEAK const PinMap PinMap_PWM[] = {
    // Heaters
    {PA_1,       PWM_2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 2, 0)}, // HB (Heated Bed)
    {PA_2,       PWM_2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 3, 0)}, // HE0 (Hotend 0)
    {PA_3,       PWM_2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 4, 0)}, // HE1 (Hotend 1)
    // Fans
    {PA_8,       PWM_1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM1, 1, 0)}, // FAN0
    {PE_5,       PWM_9,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF3_TIM9, 1, 0)}, // FAN1
    {PD_12,      PWM_4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 1, 0)}, // FAN2
    {PD_13,      PWM_4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 2, 0)}, // FAN3
    {PD_14,      PWM_4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 3, 0)}, // FAN4
    {PD_15,      PWM_4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 4, 0)}, // FAN5
    // Servo
    {PB_6,       PWM_4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 1, 0)}, // PROBE_PWM (BLTouch)
    {NC, NC, 0}
};

//*** SPI Interfaces ***

MBED_WEAK const PinMap PinMap_SPI_MOSI[] = {
    // SPI1 - TMC Drivers
    {PA_7,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI1)},  // SPI1_MOSI
    // SPI2 - Auxiliary
    {PC_3,       SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // SPI2_MOSI
    // SPI3 - Display
    {PB_5,       SPI_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF6_SPI3)},  // SPI3_MOSI
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_SPI_MISO[] = {
    // SPI1 - TMC Drivers
    {PA_6,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI1)},  // SPI1_MISO
    // SPI2 - Auxiliary
    {PC_2,       SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // SPI2_MISO
    // SPI3 - Display
    {PB_4,       SPI_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF6_SPI3)},  // SPI3_MISO
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_SPI_SCLK[] = {
    // SPI1 - TMC Drivers
    {PA_5,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI1)},  // SPI1_SCK
    // SPI2 - Auxiliary
    {PB_13,      SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // SPI2_SCK
    // SPI3 - Display
    {PB_3,       SPI_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF6_SPI3)},  // SPI3_SCK
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_SPI_SSEL[] = {
    // SPI1 - TMC Drivers and SD Card
    {PA_4,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // SD_CS
    {PC_4,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER0_CS
    {PD_11,      SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER1_CS
    {PC_6,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER2_CS
    {PC_7,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER3_CS
    {PF_2,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER4_CS
    {PE_4,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER5_CS
    {PE_1,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER6_CS
    {PD_3,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER7_CS
    {PF_8,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // MAX31865_CS
    // SPI2 - Auxiliary
    {PB_12,      SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // SPI2_NSS
    // SPI3 - Display
    //{PA_15,      SPI_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF6_SPI3)},  // SPI3_NSS
    {NC, NC, 0}
};


// Step Pins
MBED_WEAK const PinMap PinMap_STEPPER_STEP[] = {
    {PF_13,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER0_STEP (X)
    {PG_0,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER1_STEP (Y)
    {PF_11,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER2_STEP (Z)
    {PG_4,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER3_STEP (E0)
    {PF_9,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER4_STEP (E1)
    {PC_13,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER5_STEP (E2)
    {PE_2,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER6_STEP (E3)
    {PE_6,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER7_STEP (E4)
    {NC, NC, 0}
};

// Direction Pins
MBED_WEAK const PinMap PinMap_STEPPER_DIR[] = {
    {PF_12,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER0_DIR (X)
    {PG_1,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER1_DIR (Y)
    {PG_3,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER2_DIR (Z)
    {PC_1,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER3_DIR (E0)
    {PF_10,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER4_DIR (E1)
    {PF_0,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER5_DIR (E2)
    {PE_3,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER6_DIR (E3)
    //{PA_14,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER7_DIR (E4)
    {NC, NC, 0}
};

// Enable Pins (Active Low)
MBED_WEAK const PinMap PinMap_STEPPER_ENABLE[] = {
    {PF_14,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_PULLUP, 0)},  // !DRIVER0_EN (X)
    {PF_15,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_PULLUP, 0)},  // !DRIVER1_EN (Y)
    {PG_5,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_PULLUP, 0)},  // !DRIVER2_EN (Z)
    {PA_0,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_PULLUP, 0)},  // !DRIVER3_EN (E0)
    {PG_2,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_PULLUP, 0)},  // !DRIVER4_EN (E1)
    {PF_1,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_PULLUP, 0)},  // !DRIVER5_EN (E2)
    {PD_4,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_PULLUP, 0)},  // !DRIVER6_EN (E3)
    {PE_0,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_PULLUP, 0)},  // !DRIVER7_EN (E4)
    {NC, NC, 0}
};

//*** Endstops and Probe ***

MBED_WEAK const PinMap PinMap_ENDSTOPS[] = {
    // Main axis endstops
    {PG_6,       PIN_INPUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},  // X_MIN
    {PG_9,       PIN_INPUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},  // X_MAX
    {PG_10,      PIN_INPUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},  // Y_MIN
    {PG_11,      PIN_INPUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},  // Y_MAX
    {PG_12,      PIN_INPUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},  // Z_MIN
    {PG_13,      PIN_INPUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},  // Z_MAX
    // Extra endstops
    {PG_14,      PIN_INPUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},  // E_MIN
    {PG_15,      PIN_INPUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},  // E_MAX
    {NC, NC, 0}
};

// Probe Pins (BLTouch)
MBED_WEAK const PinMap PinMap_PROBE[] = {
    {PB_6,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4)},  // PROBE_PWM (Servo)
    {PB_7,       PIN_INPUT,  STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},              // PROBE_SENSE
    {PC_5,       PIN_INPUT,  STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},              // PROBE_IN (Z-Probe)
		{PC_0,      PIN_INPUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)}, // PWR DET
    {NC, NC, 0}
};

//*** Temperature Control ***

// Heaters (PWM)
MBED_WEAK const PinMap PinMap_HEATER[] = {
    {PA_1,       PWM_2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 2, 0)}, // HB (Heated Bed)
    {PA_2,       PWM_2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 3, 0)}, // HE0 (Hotend 0)
    {PA_3,       PWM_2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 4, 0)}, // HE1 (Hotend 1)
    {PB_10,      PWM_2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 5, 0)}, // HE2 (Hotend 2)
    {PB_11,      PWM_2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 6, 0)}, // HE3 (Hotend 3)
    {NC, NC, 0}
};

// Fans (PWM)
MBED_WEAK const PinMap PinMap_FAN[] = {
    {PA_8,       PWM_1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM1, 1, 0)}, // FAN0
    {PE_5,       PWM_9,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF3_TIM9, 1, 0)}, // FAN1
    {PD_12,      PWM_4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 1, 0)}, // FAN2
    {PD_13,      PWM_4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 2, 0)}, // FAN3
    {PD_14,      PWM_4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 3, 0)}, // FAN4
    {PD_15,      PWM_4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 4, 0)}, // FAN5
    {NC, NC, 0}
};

// Thermistors (ADC)
MBED_WEAK const PinMap PinMap_TEMP[] = {
    {PF_3,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 9, 0)},   // THERM0
    {PF_4,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 14, 0)},  // THERM1
    {PF_5,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 15, 0)},  // THERM2
    {PF_6,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 4, 0)},   // THERM3
    {PF_7,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 5, 0)},   // THERM4
    {NC, NC, 0}
};

//*** User Interface ***


//*** SDIO Interface ***

MBED_WEAK const PinMap PinMap_SD[] = {
    {PC_8,       SDIO_BASE, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF12_SDIO)},  // SDIO_D0
    {PC_9,       SDIO_BASE, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF12_SDIO)},  // SDIO_D1
    {PC_10,      SDIO_BASE, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF12_SDIO)},  // SDIO_D2
    {PC_11,      SDIO_BASE, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF12_SDIO)},  // SDIO_D3
    {PC_12,      SDIO_BASE, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF12_SDIO)},  // SDIO_CK
    {PD_2,       SDIO_BASE, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF12_SDIO)},  // SDIO_CMD
    {NC, NC, 0}
};

// LCD Control
MBED_WEAK const PinMap PinMap_LCD[] = {
    {PE_9,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // LCD_EN
    {PE_10,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // LCD_RS
    {PE_12,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // LCD_D4
    {PE_13,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // LCD_D5
    {PE_14,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // LCD_D6
    {PE_15,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // LCD_D7
    {NC, NC, 0}
};

// UI Controls
MBED_WEAK const PinMap PinMap_UI[] = {
    {PE_7,       PIN_INPUT,  STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},     // BTN_ENC
    {PB_1,       PIN_INPUT,  STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},     // BTN_EN2
    {PB_2,       PIN_INPUT,  STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},     // BTN_EN1
    {NC, NC, 0}
};

//*** Communication Interfaces ***

//*** SERIAL ***
MBED_WEAK const PinMap PinMap_UART_TX[] = {
    // Display UART
    {PD_8,       UART_3,  STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART3)}, // UART3_TX
    // UART2
    {PD_5,       UART_2,  STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)}, // UART2_TX (Host)
    
    // ESP UART
    {PA_9,       UART_1,  STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART1)}, // UART1_TX
 
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_UART_RX[] = {
    // Display UART
    {PD_9,       UART_3,  STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART3)}, // UART3_RX
	  // UART2
    {PD_6,       UART_2,  STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)}, // UART2_RX (Host)
   
    // ESP UART
    {PA_10,      UART_1,  STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART1)}, // UART1_RX

    {NC, NC, 0}
};

//*** CAN ***

MBED_WEAK const PinMap PinMap_CAN_RD[] = {
    {PD_0,       CAN_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF9_CAN1)},
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_CAN_TD[] = {
    {PD_1,       CAN_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF9_CAN1)},
    {NC, NC, 0}
};

//*** USB Device ***

MBED_WEAK const PinMap PinMap_USB_FS[] = {
    // USB Type-C Configuration
    {PA_11,     USB_FS, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF10_OTG_FS)}, // USB_DM
    {PA_12,     USB_FS, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF10_OTG_FS)}, // USB_DP
    {PA_9,      USB_FS, STM_PIN_DATA(STM_MODE_INPUT, GPIO_NOPULL, GPIO_AF_NONE)},     // VBUS detect
    // Remove {PA_10} since it's used for USART1_RX
    {NC, NC, 0}
};

#if (MBED_CONF_TARGET_USB_SPEED == USE_USB_HS_IN_FS)
MBED_WEAK const PinMap PinMap_USB_HS[] = {
    {PB_14,     USB_HS, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF12_OTG_HS_FS)}, // USB_HS_DM
    {PB_15,     USB_HS, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF12_OTG_HS_FS)}, // USB_HS_DP
    {NC, NC, 0}
};
#endif

//*** I2C ***

MBED_WEAK const PinMap PinMap_I2C_SDA[] = {
    {PB_9,       I2C_1, STM_PIN_DATA(STM_MODE_AF_OD, GPIO_NOPULL, GPIO_AF4_I2C1)},
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_I2C_SCL[] = {
    {PB_8,       I2C_1, STM_PIN_DATA(STM_MODE_AF_OD, GPIO_NOPULL, GPIO_AF4_I2C1)},
    {NC, NC, 0}
};

//*** System Clock Configuration ***

MBED_WEAK const PinMap PinMap_OSC[] = {
    {PC_14,      RCC_BASE, STM_PIN_DATA(STM_MODE_INPUT, GPIO_NOPULL, 0)},  // OSC32_IN
    {PC_15,      RCC_BASE, STM_PIN_DATA(STM_MODE_INPUT, GPIO_NOPULL, 0)},  // OSC32_OUT
    {NC, NC, 0}
};


// SPI1 (TMC Drivers)
MBED_WEAK const PinMap PinMap_SPI1[] = {
    {PA_7,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI1)},  // SPI1_MOSI
    {PA_6,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI1)},  // SPI1_MISO
    {PA_5,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI1)},  // SPI1_SCK
    {PA_4,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // SD_CS
    {NC, NC, 0}
};

// SPI2 (Aux)
MBED_WEAK const PinMap PinMap_SPI2[] = {
    {PC_3,       SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // SPI2_MOSI
    {PC_2,       SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // SPI2_MISO
    {PB_13,      SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // SPI2_SCK
    {PB_12,      SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // SPI2_NSS
    {NC, NC, 0}
};

// SPI3 (Display)
MBED_WEAK const PinMap PinMap_SPI3[] = {
    {PB_5,       SPI_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF6_SPI3)},  // SPI3_MOSI
    {PB_4,       SPI_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF6_SPI3)},  // SPI3_MISO
    {PB_3,       SPI_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF6_SPI3)},  // SPI3_SCK
    {PA_15,      SPI_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF6_SPI3)},  // SPI3_NSS
    {NC, NC, 0}
};

// ESP Communication
MBED_WEAK const PinMap PinMap_ESP[] = {
    {PD_7,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)},  // ESP TX
    {PD_10,      PIN_INPUT,  STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)},  // ESP RX
    {PG_7,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},            // ESP IO0
    {PG_8,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},            // ESP RESET
    {NC, NC, 0}
};

//*** System Control ***

// Power Control
MBED_WEAK const PinMap PinMap_POWER[] = {
    {PE_11,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},     // PS_ON
    {PB_0,       PWM_3,     STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM3, 3, 0)}, // STATUS_LED
    {PA_13,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},     // WORK_LED
    {NC, NC, 0}
};

//*** Special Interfaces ***

// TMC Driver Communication (UART Mode)
MBED_WEAK const PinMap PinMap_TMC_UART[] = {
    {PC_4,       UART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF8_UART4)},  // DRIVER0_CS/UART
    {PD_11,      UART_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)}, // DRIVER1_CS/UART
    {PC_6,       UART_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART3)}, // DRIVER2_CS/UART
    {PC_7,       UART_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART3)}, // DRIVER3_CS/UART
    {PF_2,       UART_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)}, // DRIVER4_CS/UART
    {PE_4,       UART_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART3)}, // DRIVER5_CS/UART
    {PE_1,       UART_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART3)}, // DRIVER6_CS/UART
    {PD_3,       UART_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)}, // DRIVER7_CS/UART
    {NC, NC, 0}
};

// TMC Driver Communication (SPI Mode)
MBED_WEAK const PinMap PinMap_TMC_SPI[] = {
    {PC_4,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER0_CS
    {PD_11,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER1_CS
    {PC_6,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER2_CS
    {PC_7,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER3_CS
    {PF_2,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER4_CS
    {PE_4,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER5_CS
    {PE_1,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER6_CS
    {PD_3,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // DRIVER7_CS
    {NC, NC, 0}
};

// Temperature Sensor Interface (MAX31865)
MBED_WEAK const PinMap PinMap_MAX31865[] = {
    {PF_8,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // MAX31865_CS
    {NC, NC, 0}
};

//*** Debug Interface ***

MBED_WEAK const PinMap PinMap_DEBUG[] = {
    {PA_13,      DEBUG_JTMS_SWDIO, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF0_SWJ)},    // SWDIO/WORK_LED
    {PA_14_ALT,  DEBUG_JTCK_SWCLK, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF0_SWJ)},    // SWCLK
    {PA_15_ALT,  DEBUG_JTDI,       STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF0_SWJ)},    // JTDI/SPI3_NSS
    {PB_3_ALT,   DEBUG_JTDO_SWO,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF0_SWJ)},    // SWO
    {PB_4_ALT,   DEBUG_JTRST,      STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF0_SWJ)},    // JTRST
    {NC, NC, 0}
};

//*** Sound Output ***

MBED_WEAK const PinMap PinMap_BEEPER[] = {
    {PE_8,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // BEEPER
    {NC, NC, 0}
};


