
#include "PeripheralPins.h"
#include "mbed_toolchain.h"

//*** Motion Control ***

MBED_WEAK const PinMap PinMap_ADC[] = {
    // Thermistor inputs
    {PA_1,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 9, 0)},   // THERM0
    {PA_2,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 14, 0)},  // THERM1
    {PA_3,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 15, 0)},  // THERM2
    {PC_15,      ADC_1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 10, 0)},  // PWR_DET
    {PC_4,       ADC_1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 10, 0)},  // SD_DET
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_ADC_Internal[] = {
    {NC, NC, 0}
};
//*** DAC ***

MBED_WEAK const PinMap PinMap_DAC[] = {
    // No DAC pins used on Octopus Pro
    {NC, NC, 0}
};


//*** UART Flow Control ***

MBED_WEAK const PinMap PinMap_UART_RTS[] = {
    // No RTS pins used on Octopus Pro
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_UART_CTS[] = {
    // No CTS pins used on Octopus Pro
    {NC, NC, 0}
};

//*** PWM ***

MBED_WEAK const PinMap PinMap_PWM[] = {
    // Heaters
    {PB_3,       PWM_2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 2, 0)}, // HB (Heated Bed)
    {PB_4,       PWM_2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 3, 0)}, // HE0 (Hotend 0)
    {PD_7,       PWM_2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 4, 0)}, // HE1 (Hotend 1)
    // Fans
    {PB_7,       PWM_1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM1, 1, 0)}, // FAN0
    {PB_6,       PWM_4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 1, 0)}, // FAN1
    {PB_5,       PWM_3, STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM3, 1, 0)}, // FAN2

    // Servo
    {PE_5,       PWM_4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 1, 0)}, // SERVOS
    {PC_13,      PWM_4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 1, 0)}, // PROBE
    {NC, NC, 0}
};

//*** SPI Interfaces ***

MBED_WEAK const PinMap PinMap_SPI_MOSI[] = {
    // SPI1 - SD Card
    {PA_7,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI1)},  // SPI1_MOSI
    // SPI2 - Auxiliary
    {PB_15,       SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // SPI2_MOSI
    // SPI3 - TMC
    {PE_13,       SPI_4, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI4)},  // SPI3_MOSI
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_SPI_MISO[] = {
    // SPI1 - SD Card
    {PA_6,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI1)},  // SPI1_MISO
    // SPI2 - WIFI
    {PB_14,       SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // SPI2_MISO
    // SPI4 - TMC
    {PE_15,       SPI_4, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI4)},  // SPI4_MISO
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_SPI_SCLK[] = {
    {PA_5,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI1)},  // SPI1_SCK
    // SPI2 - WIFI
    {PB_13,      SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // SPI2_SCK
    // SPI4 - TMC Driver
    {PE_14,       SPI_4, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI4)},  // SPI4_SCK
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_SPI_SSEL[] = {
    // SPI1 - TMC Drivers and SD Card
    {PA_4,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // SD_CS
    // SPI2 - ESP WIFI
    {PB_12,      SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // SPI2_NSS
    // SPI4 - TMC
    //{PA_15,      SPI_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI3)},  // SPI3_NSS
    {PD_5,       SPI_4, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI4)},  // DRIVER0_CS
    {PD_0,       SPI_4, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI4)},  // DRIVER1_CS
    {PE_1,       SPI_4, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI4)},  // DRIVER2_CS
    {PC_6,       SPI_4, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI4)},  // DRIVER3_CS
    {PD_12,      SPI_4, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI4)},  // DRIVER4_CS
    {NC, NC, 0}
};


// Step Pins
MBED_WEAK const PinMap PinMap_STEPPER_STEP[] = {
    {PD_4,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER0_STEP (X)
    {PA_15,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER1_STEP (Y)
    {PE_2,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER2_STEP (Z)
    {PD_15,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER3_STEP (E0)
    {PD_11,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER4_STEP (E1)
    {NC, NC, 0}
};

// Direction Pins
MBED_WEAK const PinMap PinMap_STEPPER_DIR[] = {
    {PD_3,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER0_DIR (X)
    {PA_8,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER1_DIR (Y)
    {PE_3,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER2_DIR (Z)
    {PD_14,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER3_DIR (E0)
    {PD_10,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // DRIVER4_DIR (E1)

    {NC, NC, 0}
};

// Enable Pins (Active Low)
MBED_WEAK const PinMap PinMap_STEPPER_ENABLE[] = {
    {PD_6,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_PULLUP, 0)},  // !DRIVER0_EN (X)
    {PD_1,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_PULLUP, 0)},  // !DRIVER1_EN (Y)
    {PE_0,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_PULLUP, 0)},  // !DRIVER2_EN (Z)
    {PC_7,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_PULLUP, 0)},  // !DRIVER3_EN (E0)
    {PD_13,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_PULLUP, 0)},  // !DRIVER3_EN (E0)

    {NC, NC, 0}
};

//*** Endstops and Probe ***

MBED_WEAK const PinMap PinMap_ENDSTOPS[] = {
    // Main axis endstops
    {PC_1,       PIN_INPUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},  // X_MIN
    {PC_3,       PIN_INPUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},  // X_MAX
    {PC_0,      PIN_INPUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},  // Y_MIN
    {PC_2,      PIN_INPUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},  // Y_MAX
    {PA_0,      PIN_INPUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},  // Z_MIN
    {PC_15,      PIN_INPUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},  // PWR_DET

    {NC, NC, 0}
};

// Probe Pins (BLTouch)
MBED_WEAK const PinMap PinMap_PROBE[] = {
    {PC_13,  PIN_INPUT,  STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},              // Probe
    {PE_5,   PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4)},  // Servos
    {NC, NC, 0}
};

//*** Temperature Control ***

// Heaters (PWM)
MBED_WEAK const PinMap PinMap_HEATER[] = {
    {PB_3,       PWM_2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 2, 0)}, // HB (Heated Bed)
    {PB_4,       PWM_2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 3, 0)}, // HE0 (Hotend 0)
    {PD_7,       PWM_2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM2, 3, 0)}, // HE1 (Hotend 1)

    {NC, NC, 0}
};

// Fans (PWM)
MBED_WEAK const PinMap PinMap_FAN[] = {
    {PB_7, PWM_1, STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF1_TIM1, 1, 0)},  // FAN0
    {PB_6, PWM_4, STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM4, 1, 0)},  // FAN1
    {PB_5, PWM_3, STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM3, 1, 0)},  // FAN2
    {NC, NC, 0}
};

// Thermistors (ADC)
MBED_WEAK const PinMap PinMap_TEMP[] = {
    {PA_1,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 9, 0)},   // THERM0
    {PA_2,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 14, 0)},  // THERM1
    {PA_3,       ADC_3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, GPIO_NOPULL, 0, 15, 0)},  // THERM2
    {NC, NC, 0}
};

//*** User Interface ***


// LCD Control
MBED_WEAK const PinMap PinMap_LCD[] = {
    {PB_1,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // LCD_EN
    {PB_2,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // LCD-ENCB
    {PE_7,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // LCD-ENCA
    {PB_1,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // LCD_EN
    {PE_9,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // LCD_RS
    {PE_9,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // LCD_D4
    {PE_10,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // LCD_D5
    {PE_11,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // LCD_D6
    {PE_12,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // LCD_D7
    {NC, NC, 0}
};

// UI Controls
MBED_WEAK const PinMap PinMap_UI[] = {
    {PB_0,       PIN_INPUT,  STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},     // BTN_ENC
    {PE_7,       PIN_INPUT,  STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},     // BTN_EN2
    {PB_2,       PIN_INPUT,  STM_PIN_DATA(STM_MODE_INPUT, GPIO_PULLUP, 0)},     // BTN_EN1
    {NC, NC, 0}
};

//*** Communication Interfaces ***

//*** SERIAL ***
MBED_WEAK const PinMap PinMap_UART_TX[] = {

    {PD_8,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)},  // ESP TX
    // TFT UART
    {PA_9,       UART_1,  STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART1)}, // UART1_TX

    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_UART_RX[] = {

    {PD_9,      PIN_INPUT,  STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)},  // ESP RX
    // TFT UART
    {PA_10,      UART_1,  STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART1)}, // UART1_RX

    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_QSPI[] = {
    {NC, NC, 0}
};

//*** CAN ***

MBED_WEAK const PinMap PinMap_CAN_RD[] = {
		{PB_8, FDCAN1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF9_FDCAN1)},
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_CAN_TD[] = {
   	{PB_9, FDCAN1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF9_FDCAN1)},
    {NC, NC, 0}
};

//*** SDIO Interface ***

MBED_WEAK const PinMap PinMap_SD[] = {
		{PC_8,  SDMMC1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF12_SDMMC1)},  // SDMMC1_D0
    {PC_9,  SDMMC1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF12_SDMMC1)},  // SDMMC1_D1
    {PC_10, SDMMC1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF12_SDMMC1)},  // SDMMC1_D2
    {PC_11, SDMMC1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF12_SDMMC1)},  // SDMMC1_D3
    {PC_12, SDMMC1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF12_SDMMC1)},  // SDMMC1_CK
    {PD_2,  SDMMC1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF12_SDMMC1)},  // SDMMC1_CMD
    {NC, NC, 0}
};

//*** USB Device ***
MBED_WEAK const PinMap PinMap_USB_FS[] = {
    //{PA_11,     USB_OTG_FS, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF10_OTG1_FS)}, // OTG_FS_DM
    //{PA_12,     USB_OTG_FS, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF10_OTG1_FS)}, // OTG_FS_DP
    //{PA_9,      USB_OTG_FS, STM_PIN_DATA(STM_MODE_INPUT, GPIO_NOPULL, GPIO_AF_NONE)},      // OTG_FS_VBUS
    {NC, NC, 0}
};
#if (MBED_CONF_TARGET_USB_SPEED == USE_USB_HS_IN_FS)
MBED_WEAK const PinMap PinMap_USB_HS[] = {
    //{PA_11,     USB_OTG_HS, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, USB1_OTG_HS_PERIPH_BASE)}, // USB_DM
    //{PA_12,     USB_OTG_HS, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, USB1_OTG_HS_PERIPH_BASE)}, // USB_DP
    {NC, NC, 0}
};
#endif

//*** I2C ***

MBED_WEAK const PinMap PinMap_I2C_SDA[] = {
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_I2C_SCL[] = {
    {NC, NC, 0}
};

//*** System Clock Configuration ***

MBED_WEAK const PinMap PinMap_OSC[] = {
    // Main 25MHz Crystal Oscillator
    {PH_0,       RCC_OSC_IN,  STM_PIN_DATA(STM_MODE_INPUT, GPIO_NOPULL, 0)},  // OSC_IN  - 25MHz Crystal
    {PH_1,       RCC_OSC_OUT, STM_PIN_DATA(STM_MODE_INPUT, GPIO_NOPULL, 0)},  // OSC_OUT - 25MHz Crystal

    // PC14/PC15 are not used as oscillator pins on this board
    {NC, NC, 0}
};


// SPI1 (TMC Drivers)
MBED_WEAK const PinMap PinMap_SPI1[] = {
    {PA_7,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI1)},  // SPI1_MOSI
    {PA_6,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI1)},  // SPI1_MISO
    {PA_5,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI1)},  // SPI1_SCK
    {PA_4,       SPI_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI1)},  // SD_CS
    {NC, NC, 0}
};


// SPI2 (WIFI)
MBED_WEAK const PinMap PinMap_SPI2[] = {
    {PB_15, SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // ESP-MOSI
    {PB_14, SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // ESP-MISO
    {PB_13, SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // ESP-CLK
    {PB_12, SPI_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI2)},  // ESP-CS
    {NC, NC, 0}
};

// SPI3 - TMC Drivers
MBED_WEAK const PinMap PinMap_SPI4[] = {
    {PE_13, SPI_4, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI4)},  // MOT-MOSI
    {PE_15, SPI_4, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI4)},  // MOT-MISO
    {PE_14, SPI_4, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_NOPULL, GPIO_AF5_SPI4)},  // MOT-SCK
    {NC, NC, 0}
};

// ESP Communication
MBED_WEAK const PinMap PinMap_ESP[] = {
    {PB_10,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},            // ESP IO0
    {PB_11,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},            // ESP IO4
    {PC_14,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},            // ESP RESET
    {NC, NC, 0}
};

//*** System Control ***

// Power Control
MBED_WEAK const PinMap PinMap_POWER[] = {
    {PE_11,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},     // PS_ON
    {PE_6,       PWM_3,     STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM3, 3, 0)}, // STATUS_LED
    {NC, NC, 0}
};

//*** Special Interfaces ***

// TMC Driver Communication (UART Mode)
MBED_WEAK const PinMap PinMap_TMC_UART[] = {

    {PD_5,      UART_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)}, // DRIVER1_CS/UART
    {PD_0,       UART_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART3)}, // DRIVER2_CS/UART
    {PE_1,       UART_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART3)}, // DRIVER3_CS/UART
    {PC_6,       UART_2, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)}, // DRIVER4_CS/UART
    {PD_12,       UART_3, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART3)}, // DRIVER5_CS/UART
    {NC, NC, 0}
};

// TMC Driver Communication (SPI Mode)
MBED_WEAK const PinMap PinMap_TMC_SPI[] = {
    {PD_5,      PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI4)},  // DRIVER1_CS
    {PD_0,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI4)},  // DRIVER2_CS
    {PE_1,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI4)},  // DRIVER3_CS
    {PC_6,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI4)},  // DRIVER4_CS
    {PD_12,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF5_SPI4)},  // DRIVER5_CS
    {NC, NC, 0}
};
//*** Debug Interface ***

MBED_WEAK const PinMap PinMap_DEBUG[] = {
    {PA_13,      DEBUG_JTMS_SWDIO, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF0_SWJ)},    // SWDIO/WORK_LED
    {PA_14,      DEBUG_JTCK_SWCLK, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF0_SWJ)},    // SWCLK
    {NC, NC, 0}
};

//*** Sound Output ***

MBED_WEAK const PinMap PinMap_BEEPER[] = {
    {PC_5,       PIN_OUTPUT, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0)},  // BEEPER
    {NC, NC, 0}
};


